### ISSUE TITLE
Invalid link for terminal guide

### ISSUE THREAD

**Issue by adam-sroka** [AustinT/AustinT.github.io#1]
The link on the [Austin's Links](https://github.com/AustinT/AustinT.github.io/blob/master/links/index.md) page for [A guide to become a master of the *nix terminal](https://skilstak.io/terminals/#terminal-masters) is invalid, leading a 404 error:

![link](https://user-images.githubusercontent.com/45038919/97809931-310c5380-1c68-11eb-8d44-d22aa4255f4e.png)

Obviously, this isn't a critical issue :smirk: :smile:.

**Comment by AustinT** [comment]
Looks like this website has been restructured, so I deleted the link. Thanks for pointing this out!
